### ISSUE TITLE
Documentation Inaccuracies

### ISSUE THREAD

**Issue by fretgfr** [ZiplineProject/zipline-docs#50]
As requested, while making a wrapper for the API, I noted everything that was inaccurate or confusing on the docs. The list is as follows:

- "originalName" present in File model docs but not in responses
- Folder type not documented in Models
- createdById missing from Invite model
- /api/user/urls id type is inconsistent
- 'gfycat' format specifier doesn't work when uploading files.
- POST /api/auth/invite does not return a full Invite, only 'code', 'createdById', and 'expiresAt'
- Files uploaded via the api seem to lose their 'Original-Name' header value.
- DELETE /api/user/files constantly returning 500 (Could be something on my end, but with how the docs are written my logic *should* work).
- DELETE /api/user/urls does not return what is documented.
- /api/user/folders doesn't seem to respect a false 'files' param, returns with files anyways unless it's left out.
- /api/upload 'Expires-At' says an iso format date time is invalid, while the same date works while creating an invite.

Note: This list may be incomplete, however these are the ones that I remembered to write down.

**Comment by TacticalTechJay** [comment]
Something to note with the last one. `Expires-At` should be prefixed with `date=` if you want to use ISO format. /api/auth/invite will be changed to also use `date=` prefixing for this

**Comment by fretgfr** [comment]
Interesting, impossible to have known this as it's not mentioned. Any specific timeline for auth/invite having this change?

**Comment by TacticalTechJay** [comment]
As of the latest commit, it should be changed.
